# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

target 'SouvenirApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SouvenirApp

  target 'SouvenirApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SouvenirAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SouvenirApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SouvenirApp-tvOS

  target 'SouvenirApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
